### ISSUE TITLE
Virus Scanner issue

### ISSUE THREAD

**Issue by mrvainv2** [pyro-team/bkt-toolbox#40]
Excellent addin... really appreciated. I wanted to update but Symantec Virus scanner immediately removing it.

**Comment by mrflory** [comment]
Hi, thanks for the feedback. Does this happen only with latest version 2.7.4 or also with older versions?

**Comment by mrvainv2** [comment]
Hi, the 2.7.3 version was installed without a problem.

**Comment by mrflory** [comment]
I would assume this is due to Iron-Python v2 as I have the issue with SentinelOne. Will be fixed in BKT v3 which upgrades to IPY v3.
